table DimDate
	lineageTag: 88a625dd-4ca5-44d2-b030-39c1e8444d4c

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: 1e746828-b716-4a70-b10a-f3ce1ab09ce0
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3b79e867-62a4-4c5a-95ee-d96700a0638f
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: fc866242-7c9e-4a1f-a68b-7788caaf13ba
			defaultHierarchy: LocalDateTable_237a5962-4b8f-4d78-94ef-b7d7135c0a44.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 10c54385-e9f3-4d58-91a1-6844afb98369
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: int64
		formatString: 0
		lineageTag: 816f66b5-864c-4cf8-b9fd-68e7cba193bd
		summarizeBy: sum
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 98ac57fb-a38d-41fe-85fa-2991461b5487
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 58dec8e9-0982-4ac2-86a4-10da6e7197fa
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		formatString: 0
		lineageTag: afc8badb-9eeb-40a1-b656-c55ac0d187c4
		summarizeBy: sum
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		formatString: 0
		lineageTag: b0c7813a-f4e8-4feb-929f-32aa4c494ee0
		summarizeBy: sum
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column IsWeekend
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 0d2ba4d6-648a-427d-b639-37e26c431007
		summarizeBy: none
		sourceColumn: IsWeekend

		annotation SummarizationSetBy = Automatic

	column IsHoliday
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 55a5a078-2d3c-40d3-b956-e103d3544d1d
		summarizeBy: none
		sourceColumn: IsHoliday

		annotation SummarizationSetBy = Automatic

	partition DimDate = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\CaRa801\OneDrive - HP Inc\Documents\PowerBI_Portfolio\data\DimDate.csv"),[Delimiter=",", Columns=10, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"DateKey", Int64.Type}, {"Date", type date}, {"Year", Int64.Type}, {"Quarter", Int64.Type}, {"Month", Int64.Type}, {"MonthName", type text}, {"Day", Int64.Type}, {"DayOfWeek", Int64.Type}, {"IsWeekend", type logical}, {"IsHoliday", type logical}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

